package com.thundashop.api.managers;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import com.thundashop.core.common.JsonObject2;
import com.thundashop.app.bannermanager.data.BannerSet;

public class APIBannerManager {

      private Transporter transport;

      public APIBannerManager(Transporter transport){
           this.transport = transport;
      }

     /**
     * Add a new image to an existing bannerset.<br>
     * The fileid is just an identifier and should be generated / stored by the one calling this application<br>
     * 
     * @param id The id to save on.
     * @param fileId The given file id for this image, fetched from the filemanager when uploading the image.
     * @return BannerSet
     * @throws ErrorException 
     */

     public BannerSet addImage(String id, String fileId)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("id",new Gson().toJson(id));
          data.args.put("fileId",new Gson().toJson(fileId));
          data.method = "addImage";
          data.interfaceName = "app.banner.IBannerManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<BannerSet>() {}.getType();
          BannerSet object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Initiate / create a new bannerset.
     * @param width The width for the banners
     * @param height The height for the banners.
     * @param id Specify an id if you want to override the id generation, leave empty otherwhise.
     * @return BannerSet
     * @throws ErrorException 
     */

     public BannerSet createSet(int width, int height, String id)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("width",new Gson().toJson(width));
          data.args.put("height",new Gson().toJson(height));
          data.args.put("id",new Gson().toJson(id));
          data.method = "createSet";
          data.interfaceName = "app.banner.IBannerManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<BannerSet>() {}.getType();
          BannerSet object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Delete a given banner set.
     * 
     * @param id The id for the bannerset to delete.
     * @return BannerSet
     * @throws ErrorException 
     */

     public BannerSet deleteSet(String id)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("id",new Gson().toJson(id));
          data.method = "deleteSet";
          data.interfaceName = "app.banner.IBannerManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<BannerSet>() {}.getType();
          BannerSet object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch an existing bannerset.
     * @param id The id for the bannerset to fetch, if the id does not exists, it will be created.
     * @return BannerSet
     * @throws ErrorException 
     */

     public BannerSet getSet(String id)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("id",new Gson().toJson(id));
          data.method = "getSet";
          data.interfaceName = "app.banner.IBannerManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<BannerSet>() {}.getType();
          BannerSet object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Add a product to a given image.
     * @param bannerSetId The id of the bannerset which holds the images.
     * @param imageId The image id to link a product to.
     * @param productId The id of the product to be linked.
     * @return BannerSet
     * @throws ErrorException 
     */

     public BannerSet linkProductToImage(String bannerSetId, String imageId, String productId)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("bannerSetId",new Gson().toJson(bannerSetId));
          data.args.put("imageId",new Gson().toJson(imageId));
          data.args.put("productId",new Gson().toJson(productId));
          data.method = "linkProductToImage";
          data.interfaceName = "app.banner.IBannerManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<BannerSet>() {}.getType();
          BannerSet object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Remove an already existing image from a given bannerset.
     * @param bannerSetId The id for the bannerset.
     * @param fileId The file id to remove.
     * @return BannerSet
     * @throws ErrorException 
     */

     public BannerSet removeImage(String bannerSetId, String fileId)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("bannerSetId",new Gson().toJson(bannerSetId));
          data.args.put("fileId",new Gson().toJson(fileId));
          data.method = "removeImage";
          data.interfaceName = "app.banner.IBannerManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<BannerSet>() {}.getType();
          BannerSet object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Update a given bannerset.<br>
     * If the id of the bannerset does not exists, it will automatically create one for you.<br>
     * 
     * @param set The bannerset to save.
     * @return BannerSet
     * @throws ErrorException 
     */

     public BannerSet saveSet(BannerSet set)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("set",new Gson().toJson(set));
          data.method = "saveSet";
          data.interfaceName = "app.banner.IBannerManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<BannerSet>() {}.getType();
          BannerSet object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

}
