package com.thundashop.api.managers;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import com.thundashop.core.common.JsonObject2;
import com.thundashop.app.footermanager.data.Configuration;

public class APIFooterManager {

      private Transporter transport;

      public APIFooterManager(Transporter transport){
           this.transport = transport;
      }

     /**
     * Get the current configuration.
     * @return Configuration
     * @throws ErrorException 
     */

     public Configuration getConfiguration()  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.method = "getConfiguration";
          data.interfaceName = "app.footer.IFooterManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<Configuration>() {}.getType();
          Configuration object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Change the layout for the columns.<br>
     * Defaults to 1 if nothing else is set.<br>
     * @param numberOfColumns The number of columns you want to display.
     * @throws ErrorException 
     */

     public Configuration setLayout(Integer numberOfColumns)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("numberOfColumns",new Gson().toJson(numberOfColumns));
          data.method = "setLayout";
          data.interfaceName = "app.footer.IFooterManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<Configuration>() {}.getType();
          Configuration object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Change the type of a given column.
     * @param column The column it regards
     * @param type The type,0 for text, 1 for list.
     * @return Configuration
     * @throws ErrorException 
     */

     public Configuration setType(Integer column, Integer type)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("column",new Gson().toJson(column));
          data.args.put("type",new Gson().toJson(type));
          data.method = "setType";
          data.interfaceName = "app.footer.IFooterManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<Configuration>() {}.getType();
          Configuration object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

}
