package com.thundashop.api.managers;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import com.thundashop.core.common.JsonObject2;
import com.thundashop.app.logomanager.data.SavedLogo;

public class APILogoManager {

      private Transporter transport;

      public APILogoManager(Transporter transport){
           this.transport = transport;
      }

     /**
     * Remove the current logo.
     * @return void
     * @throws ErrorException 
     */

     public void deleteLogo()  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.method = "deleteLogo";
          data.interfaceName = "app.logo.ILogoManager";
          String result = transport.send(data);
     }

     /**
     * Get the logo file id.
     * @return SavedLogo
     * @throws ErrorException 
     */

     public SavedLogo getLogo()  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.method = "getLogo";
          data.interfaceName = "app.logo.ILogoManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<SavedLogo>() {}.getType();
          SavedLogo object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Set a logo to your webshop.
     * @param fileId The file id generated by the one storing this.
     * @return void
     * @throws ErrorException 
     */

     public void setLogo(String fileId)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("fileId",new Gson().toJson(fileId));
          data.method = "setLogo";
          data.interfaceName = "app.logo.ILogoManager";
          String result = transport.send(data);
     }

}
